<!DOCTYPE html>
<html>
<head>
<link rel="stylesheet" type="text/css" href="style.css">
</head>
<body>
<div class='part2'>  

<h2>Abstract Expressionism: Concepts, Styles and Trends</h2>
<h3><br />Building upon Surrealism</h3>
<p>Surrealism was an original influence on the themes and concepts of the Abstract Expressionists. Although the American painters were uneasy with the overt Freudian symbolism of the European movement, they were still inspired by its interests in the unconscious, as well as its strain of primitivism and preoccupation with mythology. Many were particularly interested in the ideas of the Swiss psychiatrist Carl Jung, who believed that elements of a collective unconscious had been handed down through the ages by means of archetypal symbols, or primordial images, which had become recurrent motifs.</p>
<p>Before he was making his drip paintings, Pollock's interest in primeval themes appeared often. In his She-Wolf piece, which he described "came into existence because I had to paint it," a somber wolf is overlaid with lines and swirls. Although the artist refused to discuss its content, it was made as the world struggled with global crisis and has been compared to the myth of the city of Rome's birth in which the wolf suckled the twin founders Romulus and Remus. Another artist, Adolph Gottlieb, frequently included archetypal symbolism in his paintings. A cross, an egg, or an arrow might appear to express basic psychological ideas that were universally familiar.</p>
<h3><br />Color Field Painting</h3>
<p>The emerging Abstract Expressionist artists had an impetus to move away from the biomorphic Surrealism of Mir&oacute; and Picasso, and toward an increasingly reductive style that emphasized a more personal expression. Still, Rothko, and Newman are typical of this progression as they ventured into the world of color as expressive, emotional object in its own right. Still created canvases marked by bold colors that were torn up and ruptured by other juxtaposing textures and forms, angular, uneven and vivid. Rothko experimented with abstract symbols in the early 1940s before moving towards entirely abstract fields of color. Newman similarly sought an approach that might strip away all extraneous motifs and communicate everything through one powerfully resonant symbol. Newman's 'zip' paintings presented vertical bands of color painted down the center of a canvas, which served to unify rather than divide the piece.</p>
<p>Although some would later argue that Color Field Painting represented a new manifestation of a long tradition of sublime landscape (connected to a long-running topic of The Sublime in Art, noted theorist of the time Clement Greenberg viewed the work of Still, Rothko, and Newman as an evolution of formalism thus defining a fresh stream within Abstract Expressionism. Formalism was not interested in the contents of the work as much as analyzing the lines, color, and forms presented - a dissection of the way paintings were made and their purely visual aspects.</p>
<h3>Action Painting</h3>
<p>Greenberg also championed Pollock's "drip" paintings in a formalist regard (as an exciting and vast new way to look at color splotches and spontaneous paint forms) although the work was most known for catapulting Abstract Expressionism's other main style - that of action painting. Harold Rosenberg, another important critic of the time, explained in a 1952 article for ART News entitled "The American Action Painters": "At a certain moment the canvas began to appear to one American painter after another as an arena in which to act - rather than a space in which to reproduce, redesign, analyze or 'express' an object, actual or imagined. What was to go on the canvas was not a picture but an event."</p>
<p>Rosenberg presented an insightful realization of what painters like Pollock, Kline and de Kooning all had in common. For them, the painting was seen only as a physical manifestation of the actual work of art, which was the process of making the painting. The spontaneous actions of the painter, the random drips and brush strokes, all represented a struggle or dance with the subconscious to unloose its contents through pure expression.</p>
<p>But this creative process was not without considerations toward control either. Pollock considered his drip technique to be, at least in part, a means of harnessing his unconscious; the effects thus laid bare for all to see on the surface of the canvas. But like many others, Pollock also insisted on an element of control in his method - as he once said, "No chaos, damn it!" - and he believed that the "drips" were powerfully expressive, rather than being merely random accumulations of paint. Indeed, they were self-expressive. Many Abstract Expressionists whose embrace of chaos was balanced by an impulse toward control shared the ambivalence in Pollock's attitude. This paradox explains much of the energetic tumult one finds in the work of many so-called "action painters" including de Kooning, Franz Kline and Robert Motherwell. In part it led to the "all-over" effect, which one sees in Pollock's mature work, and in de Kooning's abstract paintings of the late 1940s, in which forms seem to be dispersed evenly across the canvas - composure in the midst of chaos.</p>
<p>Many Abstract Expressionists of the time straddled both Color Field and Action Painting with their work. In Helen Frankenthaler's early career, her canvases were a mix of pleasant blotches of color interspersed with loosely strategic forms. But she would go on to become one of the most famous Color Field painters of our time with her signature giant canvases stained with large washes of color, laid down in very physical fashion by large mops and squeegees.</p>
<h3>Minorities of Abstraction</h3>
<p>During the 1940s and 50s, many female painters in New York and San Francisco were producing work in tandem with their more highly publicized male counterparts, yet they remained largely absent from the literature, textbooks and documentation of the times. Abstract Expressionism was often characterized as a robustly masculine, white man's field, cutting a bold and aggressive swath through the softer aspects of fine art. But women like Mary Abbott, Jay DeFeo, Perle Fine, Helen Frankenthaler, Sonia Gechtoff, Judith Godwin, Grace Hartigan, Elaine de Kooning, Lee Krasner, Joan Mitchell, Deborah Remington, and Ethel Schwabacher were also experimenting with material and process to free themselves from previous artistic conventions. Although very individualized in essence, the work of these female artists often presented expressions in response to recurring themes such as place, seasons, or references from literature, dance and music. Similarly, African American artists Norman Lewis, who used bright expressive palettes and calligraphic lines to express the eternal conflict between joy and plight within his racial community; and Ed Clark, who was one of the early users of shaped canvases, were important contributors to the movement who flew low under the public's radar of the time.</p>
</div>
</body>
</html>